#===============================================================#
#========================== Test data ==========================#
#===============================================================#

#test_credentials=test@gmail.com/{crypt:8O9iA4+f3nMzz85szmvKmQ==}
valid.name=Example Name
valid.email=example@email.com

credentials.user=user
credentials.password={crypt:X6EqeDkRcH/bFl2oEnE0Pg==}