#selenium_url=http://localhost:4723/wd/hub
selenium_url=http://localhost:4723
capabilities.automationName=uiautomator2
capabilities.deviceName=Android Emulator
capabilities.udid=emulator-5554
#capabilities.deviceName=Android Smartphone
#capabilities.udid=${DEVICE_UDID}
capabilities.deviceType=phone
capabilities.platformName=Android

capabilities.browserName=chrome
capabilities.chromedriverAutodownload=true

#capabilities.appPackage=com.android.chrome
#capabilities.appActivity=com.android.chrome.HomeActivity
#capabilities.app=https://qaprosoft.s3-us-west-2.amazonaws.com/carinademoexample.apk
# to open an app