selenium_url=http://localhost:4723
capabilities.platformName=iOS
capabilities.deviceName=iPhone 17
capabilities.deviceType=phone
capabilities.platformVersion=26.4
capabilities.automationName=XCUITest
capabilities.udid=6664B12A-93D2-4150-903C-33DBC780AB67
#capabilities.app=https://qaprosoft.s3-us-west-2.amazonaws.com/carinademoexample.zip

capabilities.browserName=safari

capabilities.useNewWDA=true
capabilities.clearSystemFiles=true
#capabilities.showXcodeLog=true
#capabilities.wdaLaunchTimeout=120000
#capabilities.wdaConnectionTimeout=240000
#capabilities.wdaStartupRetries=3
capabilities.shouldUseSingletonTestManager=false
#capabilities.wdaStartupRetryInterval=20000
#capabilities.prebuildWDA=true